// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRTzFBD2jn0Tt_OFEjgPyDruaDNtN7Ys',
    appId: '1:294769528232:web:f8c4585b109e1e2083619d',
    messagingSenderId: '294769528232',
    projectId: 'bwaflutix-2139c',
    authDomain: 'bwaflutix-2139c.firebaseapp.com',
    databaseURL: 'https://bwaflutix-2139c.firebaseio.com',
    storageBucket: 'bwaflutix-2139c.appspot.com',
    measurementId: 'G-VEY11Q3LPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCex5GaD69AcUNvMH8obwUdOVPzCTVz3NA',
    appId: '1:294769528232:android:0984efc4d8f410db83619d',
    messagingSenderId: '294769528232',
    projectId: 'bwaflutix-2139c',
    databaseURL: 'https://bwaflutix-2139c.firebaseio.com',
    storageBucket: 'bwaflutix-2139c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB96XJMCaoMpB9h7t05kRLO0c5EoLqNgx8',
    appId: '1:294769528232:ios:775fe572a0e59fd183619d',
    messagingSenderId: '294769528232',
    projectId: 'bwaflutix-2139c',
    databaseURL: 'https://bwaflutix-2139c.firebaseio.com',
    storageBucket: 'bwaflutix-2139c.appspot.com',
    iosBundleId: 'com.example.kamiBantu',
  );
}
